/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Wave_Output_aliases.h"
#include "Wave_Output.h"
#include "I2S_Clock.h"
#include "I2S.h"
#include "I2S_PVT.h"
#include "WaveDAC8.h"
#include "TxDMA_0_dma.h"
#include "RxDMA_1_dma.h"
#include "RxDMA_0_dma.h"
#include "UART.h"
#include "TxDMA_1_dma.h"
#include "ADC_SAR.h"
#include "WaveDAC8_DacClk.h"
#include "WaveDAC8_Wave1_DMA_dma.h"
#include "WaveDAC8_Wave2_DMA_dma.h"
#include "WaveDAC8_VDAC8.h"
#include "UART_IntClock.h"
#include "ADC_SAR_IRQ.h"
#include "ADC_SAR_theACLK.h"
#include "ADC_SAR_Bypass_aliases.h"
#include "ADC_SAR_Bypass.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

